SELECT
    CASE
        WHEN BIRTHDAY = (SELECT MAX(BIRTHDAY) FROM worker) THEN 'YOUNGEST'
        WHEN BIRTHDAY = (SELECT MIN(BIRTHDAY) FROM worker) THEN 'OLDEST'
    END AS TYPE,
    NAME,
    BIRTHDAY
FROM worker
WHERE BIRTHDAY  = (SELECT MAX(BIRTHDAY) FROM worker)
OR BIRTHDAY = (SELECT MIN(BIRTHDAY) FROM worker)